input {
  file { path => "/data/botsv1.iis.json" start_position => "beginning" sincedb_path => "/usr/share/logstash/data/.sincedb_iis" codec => "json" tags => ["iis"] }
  file { path => "/data/botsv1.fgt_event.json" start_position => "beginning" sincedb_path => "/usr/share/logstash/data/.sincedb_fgt" codec => "json" tags => ["fgt"] }
  file { path => "/data/botsv1.stream_http.json" start_position => "beginning" sincedb_path => "/usr/share/logstash/data/.sincedb_http" codec => "json" tags => ["http"] }
  file { path => "/data/botsv1.winregistry.json" start_position => "beginning" sincedb_path => "/usr/share/logstash/data/.sincedb_registry" codec => "json" tags => ["registry"] }
  file { path => "/data/botsv1.XmlWinEventLog_Microsoft-Windows-Sysmon-Operational.json" start_position => "beginning" sincedb_path => "/usr/share/logstash/data/.sincedb_sysmon" codec => "json" tags => ["sysmon"] }
}

filter {
  if [result] {
    ruby {
      code => "
        result_data = event.get('result')
        if result_data.is_a?(Hash)
          result_data.each do |k, v|
            if k == 'host'
              event.set('hostname', v)
            else
              event.set(k, v)
            end
          end
        end
      "
    }
    mutate {
      remove_field => [ "result" ]
    }
  }

  if "iis" in [tags] {
    mutate {
      rename => {
        "c_ip" => "src_ip"
        "s_ip" => "dest_ip"
        "s_port" => "dest_port"
        "cs_method" => "http_method"
      }
    }
  }

  mutate {
    rename => {
      "User" => "user"
      "Computer" => "hostname"
      "devname" => "hostname"
      "dvc" => "hostname"
    }
  }

  if [_time] {
    date {
      match => [
        "_time",
        "yyyy-MM-dd HH:mm:ss.SSS zzz",
        "yyyy-MM-dd'T'HH:mm:ss.SSSZ",
        "yyyy-MM-dd'T'HH:mm:ss.SSS",
        "yyyy-MM-dd HH:mm:ss.SSS",
        "yyyy-MM-dd HH:mm:ss zzz",
        "yyyy-MM-dd HH:mm:ss",
        "yyyy-MM-dd'T'HH:mm:ssZ",
        "MM/dd/yyyy HH:mm:ss",
        "UNIX"
      ]
      target => "@timestamp"
      tag_on_failure => [ "_dateparsefailure" ]
    }
  }

  mutate {
    add_tag => [ "bots_v1_ingest" ]
  }
}

output {
  if "iis" in [tags]      { elasticsearch { hosts => ["http://elasticsearch:9200"] index => "botsv1-iis" } }
  if "fgt" in [tags]      { elasticsearch { hosts => ["http://elasticsearch:9200"] index => "botsv1-fgt" } }
  if "http" in [tags]     { elasticsearch { hosts => ["http://elasticsearch:9200"] index => "botsv1-http" } }
  if "registry" in [tags] { elasticsearch { hosts => ["http://elasticsearch:9200"] index => "botsv1-registry" } }
  if "sysmon" in [tags]   { elasticsearch { hosts => ["http://elasticsearch:9200"] index => "botsv1-sysmon" } }

  stdout { codec => dots }
}